# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(420, 200)
        Form.setMinimumSize(QtCore.QSize(420, 200))
        Form.setMaximumSize(QtCore.QSize(420, 200))
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelAngle = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelAngle.setObjectName("labelAngle")
        self.gridLayout.addWidget(self.labelAngle, 0, 0, 1, 1)
        self.labelHypotenuse = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelHypotenuse.setObjectName("labelHypotenuse")
        self.gridLayout.addWidget(self.labelHypotenuse, 1, 0, 1, 1)
        self.labelArea = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelArea.setFont(font)
        self.labelArea.setWordWrap(True)
        self.labelArea.setObjectName("labelArea")
        self.gridLayout.addWidget(self.labelArea, 2, 0, 1, 1)
        self.labelPerimeter = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelPerimeter.setFont(font)
        self.labelPerimeter.setWordWrap(True)
        self.labelPerimeter.setObjectName("labelPerimeter")
        self.gridLayout.addWidget(self.labelPerimeter, 3, 0, 1, 1)
        self.buttonResult = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonResult.setObjectName("buttonResult")
        self.gridLayout.addWidget(self.buttonResult, 4, 1, 1, 1)
        self.buttonClear = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonClear.setObjectName("buttonClear")
        self.gridLayout.addWidget(self.buttonClear, 4, 0, 1, 1)
        self.buttonClose = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonClose.setObjectName("buttonClose")
        self.gridLayout.addWidget(self.buttonClose, 4, 2, 1, 1)
        self.boxHypotenuse = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxHypotenuse.setObjectName("boxHypotenuse")
        self.gridLayout.addWidget(self.boxHypotenuse, 1, 1, 1, 2)
        self.boxArea = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxArea.setReadOnly(True)
        self.boxArea.setObjectName("boxArea")
        self.gridLayout.addWidget(self.boxArea, 2, 1, 1, 2)
        self.boxPerimeter = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxPerimeter.setReadOnly(True)
        self.boxPerimeter.setObjectName("boxPerimeter")
        self.gridLayout.addWidget(self.boxPerimeter, 3, 1, 1, 2)
        self.boxAngle = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.boxAngle.setMinimum(0.1)
        self.boxAngle.setMaximum(89.99)
        self.boxAngle.setProperty("value", 30.0)
        self.boxAngle.setObjectName("boxAngle")
        self.gridLayout.addWidget(self.boxAngle, 0, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вычисление площади и периметра"))
        self.labelAngle.setText(_translate("Form", "Угол°"))
        self.labelHypotenuse.setText(_translate("Form", "Гипотенуза"))
        self.labelArea.setText(_translate("Form", "Площадь"))
        self.labelPerimeter.setText(_translate("Form", "Периметр"))
        self.buttonResult.setText(_translate("Form", "Результат"))
        self.buttonClear.setText(_translate("Form", "Очистить"))
        self.buttonClose.setText(_translate("Form", "Закрыть"))
