# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(686, 322)
        Form.setMinimumSize(QtCore.QSize(686, 322))
        Form.setMaximumSize(QtCore.QSize(686, 322))
        self.labelGraph = QtWidgets.QLabel(parent=Form)
        self.labelGraph.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.labelGraph.setText("")
        self.labelGraph.setScaledContents(True)
        self.labelGraph.setObjectName("labelGraph")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(430, 20, 251, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.boxLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.boxLayout.setContentsMargins(0, 0, 0, 0)
        self.boxLayout.setObjectName("boxLayout")
        self.boxR = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxR.setText("")
        self.boxR.setReadOnly(False)
        self.boxR.setObjectName("boxR")
        self.boxLayout.addWidget(self.boxR, 0, 1, 1, 1)
        self.labelR = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelR.setFont(font)
        self.labelR.setWordWrap(True)
        self.labelR.setObjectName("labelR")
        self.boxLayout.addWidget(self.labelR, 0, 0, 1, 1)
        self.boxX = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxX.setReadOnly(False)
        self.boxX.setObjectName("boxX")
        self.boxLayout.addWidget(self.boxX, 1, 1, 1, 1)
        self.labelY = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelY.setFont(font)
        self.labelY.setWordWrap(True)
        self.labelY.setObjectName("labelY")
        self.boxLayout.addWidget(self.labelY, 2, 0, 1, 1)
        self.labelX = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelX.setFont(font)
        self.labelX.setWordWrap(True)
        self.labelX.setObjectName("labelX")
        self.boxLayout.addWidget(self.labelX, 1, 0, 1, 1)
        self.boxY = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxY.setReadOnly(False)
        self.boxY.setObjectName("boxY")
        self.boxLayout.addWidget(self.boxY, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(430, 220, 251, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.computeLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.computeLayout.setContentsMargins(0, 0, 0, 0)
        self.computeLayout.setObjectName("computeLayout")
        self.buttonCompute = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.buttonCompute.setObjectName("buttonCompute")
        self.computeLayout.addWidget(self.buttonCompute, 0, 0, 1, 1)
        self.boxResult = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.boxResult.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.boxResult.setReadOnly(True)
        self.boxResult.setObjectName("boxResult")
        self.computeLayout.addWidget(self.boxResult, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "График и точка"))
        self.labelR.setText(_translate("Form", "Число R"))
        self.labelY.setText(_translate("Form", "Y точки"))
        self.labelX.setText(_translate("Form", "X точки"))
        self.buttonCompute.setText(_translate("Form", "Вычислить"))
