# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(708, 470)
        Form.setMinimumSize(QtCore.QSize(708, 470))
        Form.setMaximumSize(QtCore.QSize(708, 470))
        self.box = QtWidgets.QLineEdit(parent=Form)
        self.box.setGeometry(QtCore.QRect(30, 100, 641, 271))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.box.setFont(font)
        self.box.setObjectName("box")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab8"))
