# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 244)
        Form.setMinimumSize(QtCore.QSize(680, 244))
        Form.setMaximumSize(QtCore.QSize(680, 244))
        self.labelGraph = QtWidgets.QLabel(parent=Form)
        self.labelGraph.setGeometry(QtCore.QRect(12, 10, 221, 211))
        self.labelGraph.setText("")
        self.labelGraph.setPixmap(QtGui.QPixmap("graph.png"))
        self.labelGraph.setScaledContents(True)
        self.labelGraph.setObjectName("labelGraph")
        self.labelShotCount = QtWidgets.QLabel(parent=Form)
        self.labelShotCount.setGeometry(QtCore.QRect(260, 30, 151, 16))
        self.labelShotCount.setObjectName("labelShotCount")
        self.boxShot = QtWidgets.QSpinBox(parent=Form)
        self.boxShot.setGeometry(QtCore.QRect(410, 30, 251, 22))
        self.boxShot.setMinimum(1)
        self.boxShot.setMaximum(999)
        self.boxShot.setObjectName("boxShot")
        self.buttonStart = QtWidgets.QPushButton(parent=Form)
        self.buttonStart.setGeometry(QtCore.QRect(260, 100, 401, 121))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.buttonStart.setFont(font)
        self.buttonStart.setObjectName("buttonStart")
        self.labelRad = QtWidgets.QLabel(parent=Form)
        self.labelRad.setGeometry(QtCore.QRect(260, 60, 151, 16))
        self.labelRad.setObjectName("labelRad")
        self.boxRad = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxRad.setGeometry(QtCore.QRect(410, 60, 251, 22))
        self.boxRad.setMaximum(999.99)
        self.boxRad.setProperty("value", 1.0)
        self.boxRad.setObjectName("boxRad")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа №6. Часть 3"))
        self.labelShotCount.setText(_translate("Form", "Количество выстрелов"))
        self.buttonStart.setText(_translate("Form", "Расстрел"))
        self.labelRad.setText(_translate("Form", "Радиус мишени"))
