# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(708, 576)
        Form.setMinimumSize(QtCore.QSize(708, 576))
        Form.setMaximumSize(QtCore.QSize(708, 576))
        self.label1 = QtWidgets.QLabel(parent=Form)
        self.label1.setGeometry(QtCore.QRect(10, 10, 691, 111))
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("task1.png"))
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label1")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 691, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout1.setObjectName("gridLayout1")
        self.buttonSort1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonSort1.setObjectName("buttonSort1")
        self.gridLayout1.addWidget(self.buttonSort1, 1, 0, 1, 1)
        self.boxResult1 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxResult1.setReadOnly(True)
        self.boxResult1.setObjectName("boxResult1")
        self.gridLayout1.addWidget(self.boxResult1, 1, 1, 1, 1)
        self.boxTask1 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxTask1.setObjectName("boxTask1")
        self.gridLayout1.addWidget(self.boxTask1, 0, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 360, 301, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setObjectName("gridLayout2")
        self.labelN2 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.labelN2.setObjectName("labelN2")
        self.gridLayout2.addWidget(self.labelN2, 1, 0, 1, 1)
        self.boxC2 = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_2)
        self.boxC2.setMaximum(100)
        self.boxC2.setProperty("value", 99)
        self.boxC2.setObjectName("boxC2")
        self.gridLayout2.addWidget(self.boxC2, 2, 1, 1, 2)
        self.labelC2 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.labelC2.setObjectName("labelC2")
        self.gridLayout2.addWidget(self.labelC2, 2, 0, 1, 1)
        self.boxN2 = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_2)
        self.boxN2.setObjectName("boxN2")
        self.gridLayout2.addWidget(self.boxN2, 1, 1, 1, 2)
        self.buttonResult2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.buttonResult2.setObjectName("buttonResult2")
        self.gridLayout2.addWidget(self.buttonResult2, 3, 0, 1, 3)
        self.label2 = QtWidgets.QLabel(parent=Form)
        self.label2.setGeometry(QtCore.QRect(10, 230, 691, 111))
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap("task2.png"))
        self.label2.setScaledContents(True)
        self.label2.setObjectName("label2")
        self.table2 = QtWidgets.QTableWidget(parent=Form)
        self.table2.setGeometry(QtCore.QRect(320, 360, 381, 192))
        self.table2.setColumnCount(3)
        self.table2.setObjectName("table2")
        self.table2.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Задачи"))
        self.buttonSort1.setText(_translate("Form", "Отсортировать"))
        self.boxResult1.setText(_translate("Form", "Не было ни выигрышей, ни проигрышей... Нас обманули!"))
        self.boxTask1.setPlaceholderText(_translate("Form", "Введите очки, полученные командой, без пробелов. Например, 3001"))
        self.labelN2.setText(_translate("Form", "Значение N"))
        self.labelC2.setText(_translate("Form", "Значение C"))
        self.buttonResult2.setText(_translate("Form", "Рассчитать"))
