# Form implementation generated from reading ui file 'ui/addElement.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form.resize(341, 119)
        Form.setMinimumSize(QtCore.QSize(341, 119))
        Form.setMaximumSize(QtCore.QSize(341, 119))
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridContent = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridContent.setContentsMargins(0, 0, 0, 0)
        self.gridContent.setObjectName("gridContent")
        self.labelName = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.gridContent.addWidget(self.labelName, 0, 0, 1, 1)
        self.boxCount = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.boxCount.setMinimum(1)
        self.boxCount.setMaximum(100)
        self.boxCount.setObjectName("boxCount")
        self.gridContent.addWidget(self.boxCount, 1, 1, 1, 1)
        self.labelCount = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelCount.setObjectName("labelCount")
        self.gridContent.addWidget(self.labelCount, 1, 0, 1, 1)
        self.gridButtons = QtWidgets.QGridLayout()
        self.gridButtons.setObjectName("gridButtons")
        self.buttonCancel = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonCancel.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridButtons.addWidget(self.buttonCancel, 0, 0, 1, 1)
        self.buttonOK = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.buttonOK.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.buttonOK.setObjectName("buttonOK")
        self.gridButtons.addWidget(self.buttonOK, 0, 1, 1, 1)
        self.gridContent.addLayout(self.gridButtons, 2, 0, 1, 2)
        self.boxName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.boxName.setObjectName("boxName")
        self.gridContent.addWidget(self.boxName, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление элемента"))
        self.labelName.setText(_translate("Form", "Название"))
        self.labelCount.setText(_translate("Form", "Количество"))
        self.buttonCancel.setText(_translate("Form", "Отмена"))
        self.buttonOK.setText(_translate("Form", "OK"))
