# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 117)
        Form.setMinimumSize(QtCore.QSize(700, 117))
        Form.setMaximumSize(QtCore.QSize(700, 117))
        self.boxY = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxY.setGeometry(QtCore.QRect(70, 20, 62, 22))
        self.boxY.setMinimum(-99.0)
        self.boxY.setObjectName("boxY")
        self.boxZ = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxZ.setGeometry(QtCore.QRect(70, 50, 62, 22))
        self.boxZ.setMinimum(-99.0)
        self.boxZ.setObjectName("boxZ")
        self.labelY = QtWidgets.QLabel(parent=Form)
        self.labelY.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.labelY.setObjectName("labelY")
        self.labelZ = QtWidgets.QLabel(parent=Form)
        self.labelZ.setGeometry(QtCore.QRect(30, 50, 16, 16))
        self.labelZ.setObjectName("labelZ")
        self.boxA = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxA.setGeometry(QtCore.QRect(200, 20, 62, 22))
        self.boxA.setMinimum(-99.0)
        self.boxA.setProperty("value", 1.0)
        self.boxA.setObjectName("boxA")
        self.labelB = QtWidgets.QLabel(parent=Form)
        self.labelB.setGeometry(QtCore.QRect(160, 50, 16, 16))
        self.labelB.setObjectName("labelB")
        self.labelA = QtWidgets.QLabel(parent=Form)
        self.labelA.setGeometry(QtCore.QRect(160, 20, 16, 16))
        self.labelA.setObjectName("labelA")
        self.boxB = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxB.setGeometry(QtCore.QRect(200, 50, 62, 22))
        self.boxB.setMinimum(-99.0)
        self.boxB.setProperty("value", 99.0)
        self.boxB.setObjectName("boxB")
        self.labelFormula = QtWidgets.QLabel(parent=Form)
        self.labelFormula.setGeometry(QtCore.QRect(270, 20, 261, 51))
        self.labelFormula.setText("")
        self.labelFormula.setPixmap(QtGui.QPixmap("formula.png"))
        self.labelFormula.setScaledContents(True)
        self.labelFormula.setObjectName("labelFormula")
        self.buttonResult = QtWidgets.QPushButton(parent=Form)
        self.buttonResult.setGeometry(QtCore.QRect(20, 80, 261, 26))
        self.buttonResult.setObjectName("buttonResult")
        self.boxStep = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxStep.setGeometry(QtCore.QRect(580, 30, 62, 22))
        self.boxStep.setMinimum(0.01)
        self.boxStep.setProperty("value", 1.0)
        self.boxStep.setObjectName("boxStep")
        self.labelStep = QtWidgets.QLabel(parent=Form)
        self.labelStep.setGeometry(QtCore.QRect(540, 30, 31, 16))
        self.labelStep.setObjectName("labelStep")
        self.buttonLoad = QtWidgets.QPushButton(parent=Form)
        self.buttonLoad.setGeometry(QtCore.QRect(410, 80, 261, 26))
        self.buttonLoad.setObjectName("buttonLoad")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab9-part2"))
        self.labelY.setText(_translate("Form", "Y"))
        self.labelZ.setText(_translate("Form", "Z"))
        self.labelB.setText(_translate("Form", "B"))
        self.labelA.setText(_translate("Form", "A"))
        self.buttonResult.setText(_translate("Form", "Рассчитать"))
        self.labelStep.setText(_translate("Form", "step"))
        self.buttonLoad.setText(_translate("Form", "Считать из файла"))
