# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 117)
        Form.setMinimumSize(QtCore.QSize(700, 117))
        Form.setMaximumSize(QtCore.QSize(700, 117))
        self.boxY = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxY.setGeometry(QtCore.QRect(70, 20, 62, 22))
        self.boxY.setMinimum(-99.0)
        self.boxY.setObjectName("boxY")
        self.boxZ = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxZ.setGeometry(QtCore.QRect(70, 50, 62, 22))
        self.boxZ.setMinimum(-99.0)
        self.boxZ.setObjectName("boxZ")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 16, 16))
        self.label_2.setObjectName("label_2")
        self.boxA = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxA.setGeometry(QtCore.QRect(200, 20, 62, 22))
        self.boxA.setMinimum(-99.0)
        self.boxA.setProperty("value", 1.0)
        self.boxA.setObjectName("boxA")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(160, 20, 16, 16))
        self.label_4.setObjectName("label_4")
        self.boxB = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxB.setGeometry(QtCore.QRect(200, 50, 62, 22))
        self.boxB.setMinimum(-99.0)
        self.boxB.setProperty("value", 99.0)
        self.boxB.setObjectName("boxB")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 261, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("formula.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 80, 261, 26))
        self.pushButton.setObjectName("pushButton")
        self.boxStep = QtWidgets.QDoubleSpinBox(parent=Form)
        self.boxStep.setGeometry(QtCore.QRect(580, 30, 62, 22))
        self.boxStep.setMinimum(0.01)
        self.boxStep.setProperty("value", 1.0)
        self.boxStep.setObjectName("boxStep")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(540, 30, 31, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab9-part2"))
        self.label.setText(_translate("Form", "Y"))
        self.label_2.setText(_translate("Form", "Z"))
        self.label_3.setText(_translate("Form", "B"))
        self.label_4.setText(_translate("Form", "A"))
        self.pushButton.setText(_translate("Form", "Рассчитать"))
        self.label_6.setText(_translate("Form", "step"))
