# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(624, 363)
        Form.setMinimumSize(QtCore.QSize(624, 363))
        Form.setMaximumSize(QtCore.QSize(624, 363))
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mainGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mainGrid.setContentsMargins(0, 0, 0, 0)
        self.mainGrid.setObjectName("mainGrid")
        self.usernameBox = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.usernameBox.setObjectName("usernameBox")
        self.mainGrid.addWidget(self.usernameBox, 1, 1, 1, 1)
        self.IDLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.IDLabel.setObjectName("IDLabel")
        self.mainGrid.addWidget(self.IDLabel, 2, 0, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.mainGrid.addWidget(self.usernameLabel, 1, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.messageLabel.setObjectName("messageLabel")
        self.mainGrid.addWidget(self.messageLabel, 3, 0, 1, 1)
        self.eventLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.eventLabel.setObjectName("eventLabel")
        self.mainGrid.addWidget(self.eventLabel, 0, 0, 1, 1)
        self.messageBox = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.messageBox.setObjectName("messageBox")
        self.mainGrid.addWidget(self.messageBox, 3, 1, 1, 1)
        self.IDBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.IDBox.setMaximum(999999999)
        self.IDBox.setObjectName("IDBox")
        self.mainGrid.addWidget(self.IDBox, 2, 1, 1, 1)
        self.eventBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.eventBox.setObjectName("eventBox")
        self.eventBox.addItem("")
        self.eventBox.addItem("")
        self.eventBox.addItem("")
        self.mainGrid.addWidget(self.eventBox, 0, 1, 1, 1)
        self.resultButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.resultButton.setObjectName("resultButton")
        self.mainGrid.addWidget(self.resultButton, 4, 0, 1, 2)
        self.resultBox = QtWidgets.QTextEdit(parent=Form)
        self.resultBox.setGeometry(QtCore.QRect(10, 220, 601, 131))
        self.resultBox.setMinimumSize(QtCore.QSize(601, 131))
        self.resultBox.setMaximumSize(QtCore.QSize(601, 131))
        self.resultBox.setReadOnly(True)
        self.resultBox.setObjectName("resultBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лаба 8"))
        self.IDLabel.setText(_translate("Form", "ID пользователя"))
        self.usernameLabel.setText(_translate("Form", "Имя пользователя"))
        self.messageLabel.setText(_translate("Form", "Сообщение"))
        self.eventLabel.setText(_translate("Form", "Событие"))
        self.eventBox.setItemText(0, _translate("Form", "GREETING"))
        self.eventBox.setItemText(1, _translate("Form", "NOTIFY"))
        self.eventBox.setItemText(2, _translate("Form", "DENIAL"))
        self.resultButton.setText(_translate("Form", "Результат"))
        self.resultBox.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Здесь будет результат...</p></body></html>"))
