# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(497, 349)
        self.boxF1a = QtWidgets.QLineEdit(parent=Form)
        self.boxF1a.setGeometry(QtCore.QRect(10, 10, 481, 22))
        self.boxF1a.setObjectName("boxF1a")
        self.buttonF1aGen = QtWidgets.QPushButton(parent=Form)
        self.buttonF1aGen.setGeometry(QtCore.QRect(130, 50, 171, 31))
        self.buttonF1aGen.setObjectName("buttonF1aGen")
        self.buttonF1aEval = QtWidgets.QPushButton(parent=Form)
        self.buttonF1aEval.setGeometry(QtCore.QRect(310, 50, 181, 31))
        self.buttonF1aEval.setObjectName("buttonF1aEval")
        self.buttonF1bGen = QtWidgets.QPushButton(parent=Form)
        self.buttonF1bGen.setGeometry(QtCore.QRect(130, 160, 171, 31))
        self.buttonF1bGen.setObjectName("buttonF1bGen")
        self.buttonF1bEval = QtWidgets.QPushButton(parent=Form)
        self.buttonF1bEval.setGeometry(QtCore.QRect(310, 160, 181, 31))
        self.buttonF1bEval.setObjectName("buttonF1bEval")
        self.boxF1b = QtWidgets.QLineEdit(parent=Form)
        self.boxF1b.setGeometry(QtCore.QRect(10, 120, 481, 22))
        self.boxF1b.setObjectName("boxF1b")
        self.boxF2 = QtWidgets.QLineEdit(parent=Form)
        self.boxF2.setGeometry(QtCore.QRect(10, 230, 481, 22))
        self.boxF2.setObjectName("boxF2")
        self.buttonF2Gen = QtWidgets.QPushButton(parent=Form)
        self.buttonF2Gen.setGeometry(QtCore.QRect(10, 260, 171, 31))
        self.buttonF2Gen.setObjectName("buttonF2Gen")
        self.buttonF2Eval = QtWidgets.QPushButton(parent=Form)
        self.buttonF2Eval.setGeometry(QtCore.QRect(310, 260, 181, 31))
        self.buttonF2Eval.setObjectName("buttonF2Eval")
        self.labelF1aA = QtWidgets.QLabel(parent=Form)
        self.labelF1aA.setGeometry(QtCore.QRect(20, 50, 31, 16))
        self.labelF1aA.setObjectName("labelF1aA")
        self.boxF1aA = QtWidgets.QSpinBox(parent=Form)
        self.boxF1aA.setGeometry(QtCore.QRect(50, 50, 42, 22))
        self.boxF1aA.setObjectName("boxF1aA")
        self.labelF1bK1 = QtWidgets.QLabel(parent=Form)
        self.labelF1bK1.setGeometry(QtCore.QRect(5, 160, 16, 16))
        self.labelF1bK1.setObjectName("labelF1bK1")
        self.labelF1bK2 = QtWidgets.QLabel(parent=Form)
        self.labelF1bK2.setGeometry(QtCore.QRect(70, 160, 16, 16))
        self.labelF1bK2.setObjectName("labelF1bK2")
        self.boxF1bK1 = QtWidgets.QSpinBox(parent=Form)
        self.boxF1bK1.setGeometry(QtCore.QRect(20, 160, 42, 22))
        self.boxF1bK1.setObjectName("boxF1bK1")
        self.boxF1bK2 = QtWidgets.QSpinBox(parent=Form)
        self.boxF1bK2.setGeometry(QtCore.QRect(90, 160, 42, 22))
        self.boxF1bK2.setMinimum(0)
        self.boxF1bK2.setProperty("value", 0)
        self.boxF1bK2.setObjectName("boxF1bK2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа №6. Часть 1"))
        self.boxF1a.setPlaceholderText(_translate("Form", "Введите элементы массива через пробел, либо нажмите \"Сгенерировать\""))
        self.buttonF1aGen.setText(_translate("Form", "Сгенерировать"))
        self.buttonF1aEval.setText(_translate("Form", "Выполнить"))
        self.buttonF1bGen.setText(_translate("Form", "Сгенерировать"))
        self.buttonF1bEval.setText(_translate("Form", "Выполнить"))
        self.boxF1b.setPlaceholderText(_translate("Form", "Введите элементы массива через пробел, либо нажмите \"Сгенерировать\""))
        self.boxF2.setPlaceholderText(_translate("Form", "Введите элементы массива через пробел, либо нажмите \"Сгенерировать\""))
        self.buttonF2Gen.setText(_translate("Form", "Сгенерировать"))
        self.buttonF2Eval.setText(_translate("Form", "Выполнить"))
        self.labelF1aA.setText(_translate("Form", "A"))
        self.labelF1bK1.setText(_translate("Form", "k1"))
        self.labelF1bK2.setText(_translate("Form", "k2"))
